package(
    default_visibility = [ "//visibility:public" ],
    licenses = [ "notice" ],
)

exports_files(glob(["**/*.gif"]))

filegroup(
    name = "icons",
    srcs= glob(["**/*.gif"]) + glob(["**/*.jpg"]),
)
