java_library(
	name = "jflaplib_core",
	srcs = glob(["**/*.java"]),
	visibility = [ "//visibility:public" ],
	deps = [
			"@org_apache_xmlgraphics_batik_anim//jar",
			"@org_apache_xmlgraphics_batik_dom//jar",
			"@org_apache_xmlgraphics_batik_svg_dom//jar",
			"@org_apache_xmlgraphics_batik_svggen//jar",
			"@org_apache_xmlgraphics_batik_swing//jar",
			"@org_apache_xmlgraphics_batik_awt_util//jar",
			"@org_apache_xmlgraphics_batik_util//jar",
			"@org_slf4j_slf4j_api//jar",
	]
)
